# Generated by Django 4.0.4 on 2022-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_newpost_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
