# Generated by Django 4.0.4 on 2022-06-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
