# Generated by Django 4.0.4 on 2022-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments_post_newpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='category',
            field=models.CharField(blank=True, choices=[('F', 'Frontend'), ('B', 'Backend'), ('S', 'FullStack')], max_length=2),
        ),
    ]
