# Generated by Django 4.0.4 on 2022-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_newpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='category',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('FullStack', 'FullStack')], max_length=20),
        ),
    ]
