# Generated by Django 4.0.4 on 2022-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_newpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='post_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
