# Generated by Django 4.0.4 on 2022-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_newpost_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='post_image',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='newpost',
            name='post_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
