# Generated by Django 4.0.4 on 2022-06-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_newpost_post_image_newpost_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='profile_pics',
        ),
    ]
