# Generated by Django 4.0.4 on 2022-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='comment_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
